sudo: false
language: node_js
node_js:
- '9.11.0'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
script:
- yarn build
after_success:
- bash ./deploy.sh
env:
  global:
  - GH_USER: user
  - GH_REPO: repository