baseURL = "https://anandchowdhary.com/"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en-us"
paginate = 4
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
enableRobotsTXT = true
canonifyURLs = true
theme = "anand"
title = "Anand Chowdhary"
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
[author]
  gravatarEmail = "anandchowdhary@gmail.com"
  homepageText = "Anand Chowdhary"
  name = "Anand Chowhdary"
[params]
  description = "Anand Chowdhary is a creative technologist and entrepreneur. He is the founder and CEO of Oswald Labs, an accessibility technology company."
  googleAnalytics = ""
  licence = "All Rights Reserved"
  adsenseDataAdClient = ""
  adsenseDataAdSlot = ""
  addThisId = ""
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]