[build]
  command = "yarn build"
  publish = "public"

[[redirects]]
  from = "/blog/google-docs-github/"
  to = "/blog/coffee-time/google-docs-github/"

[[redirects]]
  from = "/blog/twitter-subaccounts/"
  to = "/blog/coffee-time/twitter-subaccounts/"
